<a href="https://colab.research.google.com/github/espanolamarie/BSIS-2A-/blob/main/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
array = np.array([1,2,3,4,5])
np.median(array)

3.0

In [8]:
np.median(array)

3.0

In [10]:
np.max(array)

5

In [11]:
std_dev = np.std(array)


In [12]:
print(std_dev)

1.4142135623730951


In [14]:
np.sum(array)

15

In [16]:
reshaped_array = array.reshape((5,1))

In [17]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [18]:
array1 = np.array([1,2,3,])
array2 = np.array([4,5,6])


In [21]:
concatenated = np.concatenate((array1,array2))

In [22]:
print(concatenated)

[1 2 3 4 5 6]


In [23]:
numbers = np.linspace(0,10,2)

In [24]:
print(numbers)

[ 0. 10.]


In [25]:
range_array = np.arange(0,10,2)

In [27]:
print(range_array)

[0 2 4 6 8]
